server:
  port: 8087
spring:
  datasource:
    url: jdbc:sqlserver://209.127.228.55;databaseName=carcontracts;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Password_123#
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true