server:
  port: 8082
spring:
  datasource:
    url: jdbc:sqlserver://209.127.228.55;databaseName=carcontracts;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Password_123#
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: bAEuwlZGHSxmPsZFfEj5q2Qdycx23VX8yDGwmGUDnhSIh1vWPuGTAi9aAXU0ocNJuqJSl67vqknIuvSmliOHrA==
  expiration-ms: 2592000000
  refresh-secret: LMyBPW/4uRR2vb+zJPrgc1ex0faZthlVd0lFKn7sQQ85qzvQ9D6MMGCD+FloSuhygi9BmS9M4he1XdLekYxXIw==
  refresh-expiration-ms: 3592000000
  
application:
  service:
    name: carcontracts
    domain: api
  api:
    version: v1
    base-path: ${application.service.domain}/${application.service.name}/${application.api.version}

aws:
  region: eu-north-1
  s3:
    bucket: carcontracts

cloud:
  aws:
    credentials:
      access-key: AKIAWJXF2KW4LZTFXDUM
      secret-key: 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
    region:
      static: ${aws.region}