server:
  port: 8082
spring:
  datasource:
    url: jdbc:sqlserver://209.127.228.55;databaseName=carcontracts;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Password_123#
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: bAEuwlZGHSxmPsZFfEj5q2Qdycx23VX8yDGwmGUDnhSIh1vWPuGTAi9aAXU0ocNJuqJSl67vqknIuvSmliOHrA==
  expiration-ms: 3600000